import React from 'react'

function User({users}) {
console.log(users)

  return (
    <div> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Alias amet eum dolorum nostrum voluptatem atque corrupti doloribus minus pariatur facilis at neque aperiam, nemo cum, optio quidem perspiciatis rerum quae tempore nesciunt aut? Dignissimos esse deleniti inventore facere dolorem tenetur sapiente, quae, fugit quisquam quo iusto temporibus ipsa animi excepturi distinctio recusandae velit vel. Omnis quam eius quae aspernatur cupiditate ut aut reiciendis impedit repellat voluptas atque deleniti molestias nam, unde voluptatibus magni consequuntur voluptatum eum minima! Quae fugiat, rerum, recusandae numquam ea autem itaque dolor nobis expedita possimus enim, architecto voluptate porro! Veniam facere sed, voluptate enim nostrum reiciendis, quas culpa libero possimus assumenda laboriosam consectetur eum sint ipsum! At corporis saepe pariatur consequuntur ipsam, nisi provident molestias repellendus aliquid eum obcaecati maiores architecto facilis quas iusto explicabo possimus nesciunt delectus blanditiis? Enim eum maiores quasi quo obcaecati iure. Nostrum consectetur, autem voluptates dolor, dolores saepe doloremque delectus perferendis hic cumque earum, nisi voluptatum aliquam architecto beatae aliquid. Tempore dolorem, qui, suscipit, explicabo vitae fuga pariatur sint commodi ad voluptatum nulla facere asperiores minima aliquam illo doloremque voluptate? Ea est maxime odio sequi sapiente dolores provident natus? Aut incidunt inventore maxime alias ullam nostrum. Asperiores optio molestiae nesciunt iusto assumenda eveniet repellendus, cum porro a numquam saepe consequatur omnis veritatis vero, magni enim temporibus excepturi ipsum necessitatibus molestias corporis voluptatem, ipsa ipsam ratione. Iusto sunt aut porro voluptatum ullam facere fugiat necessitatibus eius repellat, modi voluptatem pariatur possimus consequuntur accusamus iure. Quidem doloremque, itaque eos, unde nobis consequuntur error fugiat id est dolore at accusantium a obcaecati delectus possimus. A, exercitationem quos atque quasi beatae molestias illo soluta sunt repudiandae cumque vel ducimus aperiam quod esse error unde excepturi iste delectus iure. Quis deleniti, ea eveniet quo similique modi molestias atque repudiandae ipsam quam, recusandae quidem provident. Omnis, quasi!</div>
  )
}

export default User